config/routes.rb
Rails.application.routes.draw do
  root 'recipients#index'

  resources :recipients
  resources :messages

  get 'admin' => 'admin/recipients#index'

  namespace :admin do
    root 'recipients#index'

    resources :recipients
    resources :messages
    resources :info
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/info.rb
class Info < ApplicationRecord
  validates :body, presence: true

  enum purpose: %i(morning motivation extra_motivation super_motivation)
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :recipient

  enum status: %i(success fail)
  enum purpose: %i(morning motivation)

  scope :by_status, (->(status) { where(status: status) })
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  has_many :messages, dependent: :destroy

  enum gender: %i(male female)

  validates :first_name, :last_name, :gender, :email, presence: true

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'

  http_basic_authenticate_with name: ENV['ADMIN_NAME'], password: ENV['ADMIN_PASSWORD']
end

app/controllers/admin/info_controller.rb
class Admin::InfoController < Admin::AdminController
  before_action :info, only: :edit

  def index
    @infos ||= Info.all.paginate(page: params[:page], per_page: 15)
  end

  def new
    @info = Info.new
  end

  def destroy
    info.destroy
  end

  def update
    return render :edit unless info.update(info_params)
    redirect_to admin_info_index_path
  end

  def create
    @info = Info.new(info_params)
    return render :new unless @info.valid? && @info.save
    redirect_to admin_info_index_path
  end

  private

  def info
    @info ||= Info.find(params[:id])
  end

  def info_params
    params.require(:info).permit!
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < Admin::AdminController
  def index
    @messages = Message.all.paginate(page: params[:page], per_page: 15)
  end

  def update
    MessageMailer.send("#{message.purpose}_email", message.recipient, message.body).deliver
    message.success!
  rescue => e
    Rails.logger.error(e.message)
  end

  def destroy
    message.destroy
  end

  private

  def message
    @message ||= Message.find(params[:id])
  end
end

app/controllers/admin/recipients_controller.rb
class Admin::RecipientsController < Admin::AdminController
  def index
    @recipients = Recipient.all.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    recipient.destroy
  end

  private

  def recipient
    @recipient = Recipient.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    messages = recipient ? recipient.messages : Message.all
    @data = messages.by_status(params[:status])
                    .order(:created_at)
                    .group_by { |a| a.created_at.to_datetime.to_i * 1000 }
                    .map { |key, value| [key, value.count] }

    render json: @data
  end

  private

  def recipient
    @recipient ||= Recipient.find(params[:recipient_id]) if params[:recipient_id]
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  def index
    @recipients ||= Recipient.all.paginate(page: params[:page], per_page: 10)
    @messages ||= Message.all
  end

  def show
    @messages ||= recipient.messages
  end

  private

  def recipient
    @recipient ||= Recipient.find(params[:id])
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/admin/recipients_helper.rb
module Admin::RecipientsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/admin/info/_form.html.slim
= simple_form_for @info, url: url, method: method do |f|
  = f.input :body
  = f.input :purpose, collection: Info.purposes.keys.map { |i| [i.humanize, i] }, include_blank: false
  = f.button :submit, 'Зберегти'

app/views/admin/info/_info.html.slim
tr id="admin_info_#{info.id}"
  td = info.body.truncate(100, separator: ' ')
  td = t(".#{info.purpose}")
  td
    = link_to admin_info_path(info), class: 'button', method: :delete, remote: true do
      = fa_icon 'trash'
    = link_to edit_admin_info_path(info), class: 'button' do
      = fa_icon 'pencil-square-o'

app/views/admin/info/destroy.js.slim
| $("#admin_info_#{@info.id}").hide(400);

app/views/admin/info/edit.html.slim
.info.container
  = render partial: 'form', locals: { method: :patch, url: admin_info_path }

app/views/admin/info/index.html.slim
.info.container
  .text-right
    = link_to 'Створити інформацію', new_admin_info_path, class: 'btn btn-primary'
  - if @infos.empty?
    .text-center
      span.text-warning = t('.info_empty')
  - else
    table.table.table-hover data-messages=''
      thead
        tr
          th = t('.body')
          th = t('.purpose')
          th
      tbody
        = render partial: 'info', collection: @infos
    .text-center
      = will_paginate @infos, renderer: BootstrapPagination::Rails

app/views/admin/info/new.html.slim
.info.container
  = render partial: 'form', locals: { method: :post, url: admin_info_index_path }

app/views/admin/messages/_message.html.slim
tr class = ('danger' if message.fail?) id="admin_message_#{message.id}"
  td = message.body.truncate(100, separator: ' ')
  td = t(".#{message.status}")
  td
    = link_to admin_message_path(message), class: 'button', method: :delete, remote: true do
      = fa_icon 'trash'
    - if message.fail?
      = link_to admin_message_path(message), class: 'button', method: :patch, remote: true do
        = fa_icon 'reply'

app/views/admin/messages/destroy.js.slim
| $("#admin_message_#{@message.id}").hide(400);

app/views/admin/messages/index.html.slim
.messages.container
  - if @messages.empty?
    .text-center
      span.text-warning = t('.messages_empty')
  - else
    table.table.table-hover data-messages=''
      thead
        tr
          th = t('.body')
          th = t('.status')
          th
      tbody
        = render partial: 'message', collection: @messages
    .text-center
      = will_paginate @messages, renderer: BootstrapPagination::Rails

app/views/admin/messages/update.js.slim
| $("#admin_message_#{@message.id}").replaceWith("#{j(render partial: 'message', locals: { message: @message }) }")

app/views/admin/recipients/_recipient.html.slim
tr.recipients__tr id="admin_recipient_#{recipient.id}"
  td.recipients__td--bold = recipient.first_name
  td = recipient.last_name
  td.recipients__td--link = recipient.email
  td = recipient.birthday
  td = recipient.messages.count
  td
    = link_to admin_recipient_path(recipient), class: 'recipients__button recipients__button--close', method: :delete, remote: true do
      = fa_icon('times', aria: { hidden: true })

app/views/admin/recipients/destroy.js.slim
| $("#admin_recipient_#{@recipient.id}").hide(400);

app/views/admin/recipients/index.html.slim
.recipients
  .container
    - if @recipients.any?
      span.recipients__span
        = t('.count_list',
           count: @recipients.size,
           all: @recipients.total_entries)
      .recipients-container
        table#recipients.recipients__table
          thead
            tr.recipients__head
              th.recipients__th.black = t('.first_name')
              th.recipients__th = t('.last_name')
              th.recipients__th = t('.email')
              th.recipients__th = t('.birthday')
              th.recipients__th.recipients__th--small = t('.count_messages')
              th.recipients__th
          tbody#tbody.recipients__tbody
            = render partial: 'recipient', collection: @recipients
      = will_paginate @recipients, renderer: BootstrapPagination::Rails
    - else
      .text-center
        span.text-warning = t('.recipients_empty')

app/views/layouts/_admin_nav.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container-fuild
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Головна', admin_root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to 'Користувачі', admin_recipients_path
        li
          = link_to 'Повідомлення', admin_messages_path
        li
          = link_to 'Інформація', admin_info_index_path

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Shturming
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/admin_nav'
    .admin-container
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Shturming
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = yield
    #modal.modal.fade

app/views/messages/_message.html.slim
tr class = message.status
  td = message.recipient
  td = message.body.truncate(100, separator: ' ')
  td = message.status

app/views/recipients/_message.html.slim
tr class = message.status
  td = message.body.truncate(100, separator: ' ')
  td = message.status

app/views/recipients/_messages.html.slim
- if messages.empty?
  .text-center
    span.text-warning There are no messagesa!
- else
  table.table.table-bordered data-messages=''
    tr
      th Body
      th Status
    = render partial: 'message', collection: messages

app/views/recipients/_recipient.html.slim
tr
  td = link_to recipient.email, recipient, remote: true
  td = recipient.messages.count

app/views/recipients/_show.html.slim
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      button.close data-dismiss="modal" type="button"  ×
      h3 = @recipient.email
    .modal-body
      .information
        .biography
          ul
            li.name = @recipient.full_name
            li
              => fa_icon('envelope')
              = mail_to @recipient.email
            - if @recipient.birthday
              li
                => fa_icon('gift')
                = @recipient.birthday.strftime('%b %e, %Y')
            li
              => fa_icon(@recipient.gender)
              = t(@recipient.gender)
        .messages-count
          span = @messages.count
      .chart#container_show
      / = render 'messages', messages: @messages

app/views/recipients/index.html.slim
- if @recipients.empty?
  .text-center
    span.text-warning = t('.empty')
- else
  h3 = t('.recipients')
  table.table.table-bordered data-messages=''
    tr
      th Email
      th = t('.count')
    = render partial: 'recipient', collection: @recipients
  .text-center
    = will_paginate @recipients, renderer: BootstrapPagination::Rails
  #container

app/views/recipients/show.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'show') %>');
m.modal('show');
var seriesOptions = [],
  seriesCounter = 0,
  names = ['success', 'fail'];

function createChart() {
  Highcharts.stockChart('container_show', {
    chart: {
      zoomType: 'x'
    },
    subtitle: {
      text: document.ontouchstart === undefined ?
      'Click and drag in the plot area to zoom in' : 'Pinch the chart to zoom in'
    },
    xAxis: {
      type: 'datetime'
    },
    legend: {
      enabled: false
    },
    plotOptions: {
      area: {
        fillColor: {
          linearGradient: {
            x1: 0,
            y1: 0,
            x2: 0,
            y2: 1
          },
          stops: [
            [0, Highcharts.getOptions().colors[0]],
            [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
          ]
        },
        marker: {
          radius: 2
        },
        lineWidth: 1,
        states: {
          hover: {
            lineWidth: 1
          }
        },
        threshold: null
      },
      series: {
        compare: 'percent',
        showInNavigator: true
      }
    },
    rangeSelector: {
      selected: 4
    },

    yAxis: {
      labels: {
        formatter: function () {
          return (this.value > 0 ? ' + ' : '') + this.value + '%';
        }
      },
      plotLines: [{
        value: 0,
        width: 2,
        color: 'silver'
      }]
    },

    tooltip: {
      pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',
      split: true
    },

    series: seriesOptions
  });
}

$.each(names, function (i, name) {
  $.getJSON('/messages', { status: name.toLowerCase(), recipient_id: <%= @recipient.id %> },    function (data) {

    seriesOptions[i] = {
      name: name,
      data: data
    };

    seriesCounter += 1;

    if (seriesCounter === names.length) {
      createChart();
    }
  });
});